baseURL = "https://demo.gethugothemes.com/liva/examplesite/"
disqusShortname = ""
languageCode = "en-us"
paginate = 6
summaryLength = "10"
theme = "liva-hugo"
title = "Liva | Personal blog template"
[[menu.footer]]
URL = "about/"
name = "About"
weight = 1
[[menu.footer]]
URL = "blog/"
name = "Post"
weight = 2
[[menu.footer]]
URL = "contact/"
name = "Contact"
weight = 3
[[menu.main]]
URL = "about/"
name = "O Nas"
weight = 1
[[menu.main]]
URL = "blog/"
name = "Informacje"
weight = 2
[[menu.main]]
URL = "contact/"
name = "Kontakt"
weight = 3
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "cgorka"
copyright = "| copyright &copy; 2022 by Zielona Cerekiew Website by [Rx48.eu](https://rx48.eu) [ceXar.it](https://cexar.it)|"
description = "ceXar.it"
email = "cgorka@gmail.com"
googleAnalitycsID = "Your ID"
home = "Home"
location = "Cerekiew"
#logo = "images/logo.png"
logo = "images/Cerekiew.png"

[params.cookies]
enable = true
expire_days = 2
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/venobox/venobox.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true

